trigger:
  branches:
    include:
    - '*'  # must quote since "*" is a YAML reserved character; we want a string
  paths:
    exclude:
    - '*.md'
    - /docs/

pool:
  vmImage: 'ubuntu-latest'

variables:
  tagName: '$(Build.BuildNumber)'
  repoName: 'cloudmall/merchant'
  latestImageName: '$(repoName):latest'
  imageName: '$(repoName):$(tagName)'

steps:
- task: UseDotNet@2
  displayName: 'Use .NET Core sdk'
  inputs:
    packageType: sdk
    version: 3.1.x

- script: dotnet --info
  displayName: 'dotnet info'

- script: dotnet build -c Release
  displayName: 'dotnet build'

- script: docker build -f Dockerfile -t $(imageName) -t $(latestImageName) .
  displayName: 'Docker build Script'

- script: |
    docker login -u $(dockerId) -p $(pswd)
    docker push $(imageName)
  displayName: 'Push docker image'

- script: |
    docker push $(latestImageName)
  displayName: 'Push latest image'

# - task: SSH@0
#   displayName: 'Run shell inline on remote machine'
#   inputs:
#     sshEndpoint: 'weihanli.top'
#     runOptions: inline

#     inline: |
#       kubectl set image deployment/reservation-server reservation-server=$(imageName) --record=true
